apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: claritiGISAPIDoc
  annotations:
    github.com/project-slug: jsun-clariti/claritiGISAPIDoc
spec:
  type: other
  lifecycle: unknown
  owner: JSun
