public with sharing class Constants {
    public static final String ARCGIS_TYPE_ONLINE = 'online';
    public static final String ARCGIS_TYPE_ENTERPRISE = 'enterprise';
    public static final String CONNECTION_TYPE_APPLICATION = 'application';
    public static final String CONNECTION_TYPE_USER = 'user';
    public static final Integer TOKEN_TTL_OFFSET = 5000;
    public static final String GEOMETRY_TYPE_JSON = 'JSON';
}